### ISSUE TITLE
undefined: errors.As

### ISSUE THREAD

**Issue by giddel** [cenkalti/backoff#114]
Since this morning I get an error during `docker build` of my app:
```
vendor/github.com/cenkalti/backoff/v4/retry.go:60:6: undefined: errors.As
```
I do not use the module directly, it is pulled in in dependency chain by `go mod`
Any suggestions?

**Comment by giddel** [comment]
Got it ;-)
Docker build with go v1.12 causes the error. Bumping the version to 1.14 fixes it.
